# Generated by Django 4.0.4 on 2022-05-07 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='Quantity',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
